export interface IStudent{
    academicProgram: string,
    studentId: string,
    familyName: string,
    givenName: string,
    birthDate: string,
    email: string,
    academicLevel: number,
    gpa:number,
    credits:[{
      courseCode: string,
      courseName: string,
      termCompleted: string,
      gradeEarned: string
    }],
    tentativeCourses:{
      courseId: Number,
      term: String,
      academicProgram: String,
      level: Number,
      prerequisite: [
        String
      ],
      courseCode: String,
      section: String,
      termSectionId: Number,
      enrolCapacity: Number,
      enrolTotal: Number,
      room: String,
      roomCapacity: Number,
      classStart: String,
      classEnd: String,
      classMon: String,
      classTue: String,
      classWed: String,
      classThu: String,
      classFri: String,
      dateStart: String,
      dateEnd: String,
      professor: String},
      confirmedCourses:{
        courseId: Number,
        term: String,
        academicProgram: String,
        level: Number,
        prerequisite: [
          String
        ],
        courseCode: String,
        section: String,
        termSectionId: Number,
        enrolCapacity: Number,
        enrolTotal: Number,
        room: String,
        roomCapacity: Number,
        classStart: String,
        classEnd: String,
        classMon: String,
        classTue: String,
        classWed: String,
        classThu: String,
        classFri: String,
        dateStart: String,
        dateEnd: String,
        professor: String}
  }